const sampleData = 
[
 {
        s_no: 0,
        amt_pledged: 15823,
        blurb: "'Catalysts, Explorers & Secret Keepers: Women of Science Fiction' is a take-home exhibit & anthology by the Museum of Science Fiction.",
        by: "Museum of Science Fiction",
        country: "US",
        currency: "usd",
        end_time: "2016-11-01T23:59:00-04:00",
        location: "Washington, DC",
        percentage_funded: 186,
        num_backers: 219382,
        state: "DC",
        title: "Catalysts, Explorers & Secret Keepers: Women of SF",
        type: "Town",
        url: "/projects/1608905146/catalysts-explorers-and-secret-keepers-women-of-sf?ref=discovery"
    },
    {
        s_no: 1,
        amt_pledged: 6859,
        blurb: "A unique handmade picture book for kids & art lovers about a nervous monster who finds his courage with the help of a brave little girl",
        by: "Tyrone Wells & Broken Eagle, LLC",
        country: "US",
        currency: "usd",
        end_time: "2016-11-25T01:13:33-05:00",
        location: "Portland, OR",
        percentage_funded: 8,
        num_backers: 154926,
        state: "OR",
        title: "The Whatamagump (a hand-crafted story picture book)",
        type: "Town",
        url: "/projects/thewhatamagump/the-whatamagump-a-hand-crafted-story-picture-book?ref=discovery"
    },
    {
        s_no: 2,
        amt_pledged: 17906,
        blurb: "A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters.",
        by: "Tessa Stone",
        country: "US",
        currency: "usd",
        end_time: "2016-11-23T23:00:00-05:00",
        location: "Los Angeles, CA",
        percentage_funded: 102,
        num_backers: 105857,
        state: "CA",
        title: "Not Drunk Enough Volume 1!",
        type: "Town",
        url: "/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
        },
    {
        s_no: 3,
        amt_pledged: 17906,
        blurb: "A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters.",
        by: "Tessa Stone",
        country: "US",
        currency: "usd",
        end_time: "2016-11-23T23:00:00-05:00",
        location: "Los Angeles, CA",
        percentage_funded: 102,
        num_backers: 105857,
        state: "CA",
        title: "Not Drunk Enough Volume 1!",
        type: "Town",
        url: "/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
        },
    {
        s_no: 4,
        amt_pledged: 17906,
        blurb: "A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters.",
        by: "Tessa Stone",
        country: "US",
        currency: "usd",
        end_time: "2016-11-23T23:00:00-05:00",
        location: "Los Angeles, CA",
        percentage_funded: 102,
        num_backers: 105857,
        state: "CA",
        title: "Not Drunk Enough Volume 1!",
        type: "Town",
        url: "/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
        },
    {
        s_no: 5,
        amt_pledged: 17906,
        blurb: "A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters.",
        by: "Tessa Stone",
        country: "US",
        currency: "usd",
        end_time: "2016-11-23T23:00:00-05:00",
        location: "Los Angeles, CA",
        percentage_funded: 102,
        num_backers: 105857,
        state: "CA",
        title: "Not Drunk Enough Volume 1!",
        type: "Town",
        url: "/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
        },
    {
        s_no: 6,
        amt_pledged: 17906,
        blurb: "A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters.",
        by: "Tessa Stone",
        country: "US",
        currency: "usd",
        end_time: "2016-11-23T23:00:00-05:00",
        location: "Los Angeles, CA",
        percentage_funded: 102,
        num_backers: 105857,
        state: "CA",
        title: "Not Drunk Enough Volume 1!",
        type: "Town",
        url: "/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
    },{
        s_no: 7,
        amt_pledged: 17906,
        blurb: "A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters.",
        by: "Tessa Stone",
        country: "US",
        currency: "usd",
        end_time: "2016-11-23T23:00:00-05:00",
        location: "Los Angeles, CA",
        percentage_funded: 102,
        num_backers: 105857,
        state: "CA",
        title: "Not Drunk Enough Volume 1!",
        type: "Town",
        url: "/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
        },
    {
        s_no: 8,
        amt_pledged: 17906,
        blurb: "A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters.",
        by: "Tessa Stone",
        country: "US",
        currency: "usd",
        end_time: "2016-11-23T23:00:00-05:00",
        location: "Los Angeles, CA",
        percentage_funded: 102,
        num_backers: 105857,
        state: "CA",
        title: "Not Drunk Enough Volume 1!",
        type: "Town",
        url: "/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
        },
    {
        s_no: 9,
        amt_pledged: 17906,
        blurb: "A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters.",
        by: "Tessa Stone",
        country: "US",
        currency: "usd",
        end_time: "2016-11-23T23:00:00-05:00",
        location: "Los Angeles, CA",
        percentage_funded: 102,
        num_backers: 105857,
        state: "CA",
        title: "Not Drunk Enough Volume 1!",
        type: "Town",
        url: "/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
        },
    {
        s_no: 10,
        amt_pledged: 17906,
        blurb: "A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters.",
        by: "Tessa Stone",
        country: "US",
        currency: "usd",
        end_time: "2016-11-23T23:00:00-05:00",
        location: "Los Angeles, CA",
        percentage_funded: 102,
        num_backers: 105857,
        state: "CA",
        title: "Not Drunk Enough Volume 1!",
        type: "Town",
        url: "/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
        },
    {
        s_no: 11,
        amt_pledged: 17906,
        blurb: "A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters.",
        by: "Tessa Stone",
        country: "US",
        currency: "usd",
        end_time: "2016-11-23T23:00:00-05:00",
        location: "Los Angeles, CA",
        percentage_funded: 102,
        num_backers: 105857,
        state: "CA",
        title: "Not Drunk Enough Volume 1!",
        type: "Town",
        url: "/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
        },
    {
        s_no: 12,
        amt_pledged: 17906,
        blurb: "A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters.",
        by: "Tessa Stone",
        country: "US",
        currency: "usd",
        end_time: "2016-11-23T23:00:00-05:00",
        location: "Los Angeles, CA",
        percentage_funded: 102,
        num_backers: 105857,
        state: "CA",
        title: "Not Drunk Enough Volume 1!",
        type: "Town",
        url: "/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
    },
]

export default sampleData;